package = "params"

[[errors]]
name = "MetaWrongType"
msg = "field present but does not contain a table."

[[errors]]
name = "MetaRootTemplateWrongType"
msg = "field present but contains neither a string nor a table."

[[errors]]
name = "MetaRootTemplatePathMissing"
msg = "missing required field."

[[errors]]
name = "MetaRootTemplatePathWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaRootTemplateFromWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaRootTemplateFromInvalid"
msgf = "field does not contain one of the allowed values: '%s' or '%s'."
msgp = ["\"params\"", "\"cwd\""]

[[errors]]
name = "MetaRootOutputWrongType"
msg = "field present but contains neither a string nor a table."

[[errors]]
name = "MetaRootOutputPathMissing"
msg = "missing required field."

[[errors]]
name = "MetaRootOutputPathWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaRootOutputFromWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaRootOutputFromInvalid"
msgf = "field does not contain one of the allowed values: '%s' or '%s'."
msgp = ["\"params\"", "\"cwd\""]

[[errors]]
name = "MetaPairsWrongType"
msg = "field present but does not contain an array."

[[errors]]
name = "MetaPairWrongType"
msg = "field present but does not contain a table."

[[errors]]
name = "MetaRootTemplateMissingInMultiple"
msg = "required field is required for multiple files but is missing."

[[errors]]
name = "MetaRootOutputMissingInMultiple"
msg = "required field is required for multiple files but is missing."

[[errors]]
name = "MetaPairTemplateMissing"
msg = "missing required field."

[[errors]]
name = "MetaPairTemplateWrongType"
msg = "field present but contains neither a string nor a table."

[[errors]]
name = "MetaPairTemplatePathMissing"
msg = "missing required field."

[[errors]]
name = "MetaPairTemplatePathWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaPairTemplateFromWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaPairTemplateFromInvalid"
msgf = "field does not contain one of the allowed values: '%s' or '%s'."
msgp = ["\"params\"", "\"cwd\""]

[[errors]]
name = "MetaPairOutputMissing"
msg = "missing required field."

[[errors]]
name = "MetaPairOutputWrongType"
msg = "field present but contains neither a string nor a table."

[[errors]]
name = "MetaPairOutputPathMissing"
msg = "missing required field."

[[errors]]
name = "MetaPairOutputPathWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaPairOutputFromWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaPairOutputFromInvalid"
msgf = "field does not contain one of the allowed values: '%s' or '%s'."
msgp = ["\"params\"", "\"cwd\""]

[[errors]]
name = "MetaPromptsWrongType"
msg = "field present but does not contain an array."

[[errors]]
name = "MetaPromptWrongType"
msg = "field present but does not contain a table."

[[errors]]
name = "MetaPromptNameMissing"
msg = "missing required field."

[[errors]]
name = "MetaPromptNameWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaPromptKindWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaPromptKindInvalid"
msgf = "field does not contain one of the allowed values: %v."
msgp = ["prompts.SupportedPromptKinds"]

[[errors]]
name = "MetaPromptTitleWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaPromptOptionsMissing"
msg = "required field for `select` is missing."

[[errors]]
name = "MetaPromptOptionsWrongType"
msg = "field present but does not contain an array."

[[errors]]
name = "MetaPromptOptionTitleMissing"
msg = "missing required field."

[[errors]]
name = "MetaPromptOptionTitleWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaPromptOptionWrongType"
msg = "field present but contains neither a string nor a table."

[[errors]]
name = "MetaLeftDelimWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaRightDelimWrongType"
msg = "field present but does not contain a string."

[[errors]]
name = "MetaCaseWrongType"
msg = "field present but does not contain a string."

[meta]
template = {path = "params_errors.go.tmpl", from = "params"}
output = {path = "../params/errors.go", from = "params"}
